server:
  #  address: 127.0.0.1
  address: 192.168.8.243
  port: 8088
  compression:
    enabled: true

spring:
  application:
    name: portal-web

  profiles:
    active: dev

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    database: 1
    password: 123456
  #    password: foobared

  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    check-template: false

  mobile:
    devicedelegatingviewresolver:
      enabled: true
      mobile-prefix: mobile/

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.boot: info
    org.springframework.security: info
    OThinker: debug
    com.h3bpm: debug
h3:
  cas:
    enabled: true
    server_url: http://192.168.8.243:8085
    localhost: http://192.168.8.243:8085
    success_target_url: /Portal/#/app/Workflow/MyUnfinishedWorkItem
    failure_targer_url: /Portal/#/app/Workflow/MyUnfinishedWorkItem
#    新版移动端
#  scanBasePackages : OThinker.H3.Controller.*,com.h3bpm.mobile.controller,com.h3bpm.base.controller.handler
#  旧版移动端
  scanBasePackages : OThinker.H3.Controller.*,OThinker.H3.Mobile.Controller,com.h3bpm.base.controller.handler

